### ISSUE TITLE
Add in variance-based selection rules

### ISSUE THREAD

**Issue by thcrock** [dssg/audition#4]
There are some variance-based selection rules that didn't get merged because of concerns about the first train time's variance being NaN. 

https://github.com/dssg/audition/blob/selection_rules/audition/selection_rules.py

We should figure out a workaround and add them in.

**Comment by shaycrk** [comment]
@thcrock  - I think the more selection rules PR that you just merged should resolve this, right?

**Comment by thcrock** [comment]
Yep
