### ISSUE TITLE
Utility to get initial lists

### ISSUE THREAD

**Issue by thcrock** [dssg/audition#8]
Provide some functionality for getting train_end_date and model_group_id lists with some typical options

Sounds like this is what we were reserving the name 'casting call' for.

**Comment by thcrock** [comment]
Object that takes in as kwargs:

- model group info
- batch run time
- model comment
- exp hash
- hash of feature list in mg

And spits out model group ids

For train end times, take in these model group ids and get common options. Verify that each model group has each train end time (and an evaluation for it).

**Comment by jesteria** [comment]
This issue was moved to dssg/triage#321
